<?php /** @var \Dathard\SimplePopup\Block\Popup $block */ ?>

<div id="dt-simple-popup-content">
    <?= $block->getContent() ?>
</div>
<script>
    require([
            'jquery',
            'Magento_Ui/js/modal/modal'
        ], function($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Close'),
                    class: 'dt-simple-popup-close',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#dt-simple-popup-content'));
            $('#dt-simple-popup-content').modal('openModal');
        }
    );
</script>
