<?php /** @var \Dathard\SimplePopup\Block\Popup $block */ ?>
<script>
    require([
            'Dathard_SimplePopup/js/simple-popup'
        ], function (popup) {
            window.addEventListener('scroll', initDtSimplePopup);

            function initDtSimplePopup() {
                popup.openPopup(<?= $block->getCookieTimeout() ?>);

                window.removeEventListener('scroll', initDtSimplePopup);
            }
        }
    );
</script>
